"""add device api key to machines

Revision ID: 8ffa37598d93
Revises: b3a390de57e6
Create Date: 2026-08-30 15:44:47.302094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffa37598d93'
down_revision: Union[str, Sequence[str], None] = 'b3a390de57e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('device_api_key', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_machines_device_api_key'), 'machines', ['device_api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machines_device_api_key'), table_name='machines')
    op.drop_column('machines', 'device_api_key')
    # ### end Alembic commands ###
