PRIMARY_COLOR = "#2563EB"
SUCCESS_COLOR = "#16A34A"
WARNING_COLOR = "#F59E0B"
DANGER_COLOR = "#DC2626"

BACKGROUND_COLOR = "#F8FAFC"
CARD_COLOR = "#FFFFFF"

PAGE_TITLE = "PredictGuard AI"

PAGE_ICON = "🏭"

LAYOUT = "wide"

SIDEBAR_STATE = "expanded"

APP_VERSION = "v1.0.0"
